version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}
    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${WEB_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${WEB_BASICAUTH_PASSWORD}
    ports:
      - "${WEB_MONGODB_PORT}:8081"
    depends_on:
      - mongo

  backend:
    build: .
    container_name: backend
    environment:
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_PORT: ${MONGO_DB_PORT}
      MONGO_DB_URL: mongodb://mongo:${MONGO_DB_PORT}/your-database-name
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: ["npm", "start"]

volumes:
  mongo-data:
